# Server Port Configuration
server.port=8080

# Server Port Configuration
server.port=8080

# Spring Active Profile Selection
# Set to 'local' for local PostgreSQL, or 'neon' for Cloud NeonDB
spring.profiles.active=neon

# Common Spring Data JPA Configuration for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Logging Level
logging.level.com.gameops=INFO
logging.level.org.springframework.web=INFO


