# NeonDB Cloud PostgreSQL Connection Credentials
spring.datasource.url=jdbc:postgresql://ep-autumn-thunder-atz0qgve-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_OjNxSbDnLe12
spring.datasource.driver-class-name=org.postgresql.Driver